language: java

matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
  - os: linux
    sudo: false
    dist: precise

install: "mvn -Dmaven.test.skip=true clean install --batch-mode"

script: "mvn -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true -Dcobertura.report.format=xml --fail-at-end --batch-mode cobertura:cobertura cobertura:dump-datafile"

after_success:
- bash <(curl -s https://codecov.io/bash)
